HOST: http://apis.1-9-90.net/

--- Global Dawn APIs
---
Here goes a nice big paragraph explaining what the API does, and what these docs
are. FWIW, this is Markdown, so you can put anything in here (including links,
[like this](http://ericsucks.com/)).
---

--
Social Login
The following APIs comprise the social login related functionality.
--
Get the status of the current user session. Uses cookies, so you cannot request
this on behalf of a user.
GET /apis/core/session
< 200
< Content-Type: application/json
{
  "foo": {
    "bar": [
      "lambda"
    ]
  }
}
